AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 2.6.3
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
